### ISSUE TITLE
Myprofle

### ISSUE THREAD

**Issue by eerison** [Harkunwar/attractive-typst-resume#7]
quite nice profile page 👏🏼 👏🏼 

just to share with you, that you can generate your resume using github discussion and yaml syntax in [myprofile](https://github.com/shield-wall/myprofile) project.

in the end it will be a resume like this: https://github.com/shield-wall/myprofile/discussions/723 ;)

**Comment by Harkunwar** [comment]
Hello @eerison, Thanks for sharing it here. I'll play around with it in the coming days!
